# We are going to start TensorFlow Basics here

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.19.0


In [3]:
#Creatint Tensor with constant
#function here that we can use to create
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [4]:
scalar.ndim

0

In [5]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [8]:
matrix=tf.constant([[5,9],[9,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
second_matrix=tf.constant([[5,7], [3,8],
                           [3,9],
                           [4,2],
                           [8,6]])

In [11]:
second_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [12]:
second_matrix.ndim

2

In [17]:
third_matrix=tf.constant(
    [
   [[1,2,3],
   [2,4,5]],
   [[7,9,3],
   [10,4,5]],
   [[11,2,3],
   [2,4,15]],
          ] )
third_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  5]],

       [[ 7,  9,  3],
        [10,  4,  5]],

       [[11,  2,  3],
        [ 2,  4, 15]]], dtype=int32)>

In [18]:
third_matrix.ndim

3

In [20]:
second_matrix=tf.constant([[5.6,7.3], [3.45,8.25],
                           [3.11,9.23],
                           [4.34,2.34],
                           [8.4,6.23]],dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[5.6  7.3 ]
 [3.45 8.25]
 [3.11 9.23]
 [4.34 2.34]
 [8.4  6.23]], shape=(5, 2), dtype=float32)


In [21]:
# single Number that means scalar
scalar=tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [22]:
# a number with direction
vector=tf.constant([10,10,20,30])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 20, 30], dtype=int32)>

In [24]:
# a 2-D array of numbers
matrix=tf.constant([[10,20],[30,40]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [26]:
#Tensor : an n-dimensional array of numbers (n=0,n=1,n=2.......)
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [27]:
# Find the shape,dimension,rank and size of the tensors
print("Scalar Information")
print("Shape:",scalar.shape)
print("Dimension: ",scalar.ndim)
print("Rank: ",tf.rank(scalar).numpy())
print("Size: ",tf.size(scalar))


Scalar Information
Shape: ()
Dimension:  0
Rank:  0
Size:  tf.Tensor(1, shape=(), dtype=int32)


In [29]:
print("Vector Information")
print("Shape:",vector.shape)
print("Dimension: ",vector.ndim)
print("Rank: ",tf.rank(vector).numpy())
print("Size: ",tf.size(vector))

Vector Information
Shape: (4,)
Dimension:  1
Rank:  1
Size:  tf.Tensor(4, shape=(), dtype=int32)


In [30]:
print("Matrix Information")
print("Shape:",matrix.shape)
print("Dimension: ",matrix.ndim)
print("Rank: ",tf.rank(matrix).numpy())
print("Size: ",tf.size(matrix))

Matrix Information
Shape: (2, 2)
Dimension:  2
Rank:  2
Size:  tf.Tensor(4, shape=(), dtype=int32)


In [31]:
print("Tesnor Information")
print("Shape:",tensor.shape)
print("Dimension: ",tensor.ndim)
print("Rank: ",tf.rank(tensor).numpy())
print("Size: ",tf.size(tensor))

Tesnor Information
Shape: (2, 2, 2)
Dimension:  3
Rank:  3
Size:  tf.Tensor(8, shape=(), dtype=int32)


In [32]:
#Creating Tensor using Varibale
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [33]:
changeable_tensor[0].assign(9)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [34]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [35]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [36]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [38]:
#unchangeable_tensor[0].assign(12)
#unchangeable_tensor
#this will be an error because you can't change constant tensor. They are Immutable i.e. unchangable

In [44]:
#Random Tensors
random_tensor=tf.random.Generator.from_seed(42)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [45]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.39874756, 0.54896057, 0.8244401 , ..., 0.16676903, 0.63728046,
        0.7476535 ],
       [0.24923015, 0.6887468 , 0.04297066, ..., 0.09731793, 0.73944056,
        0.20435023],
       [0.21640241, 0.72182214, 0.15910757, ..., 0.89945376, 0.14467645,
        0.8007077 ],
       ...,
       [0.43915415, 0.28382063, 0.71524024, ..., 0.727525  , 0.11748576,
        0.2682165 ],
       [0.6326467 , 0.935701  , 0.31172776, ..., 0.28301   , 0.86319757,
        0.28606284],
       [0.18462384, 0.4083178 , 0.41436327, ..., 0.60521483, 0.37081027,
        0.9365988 ]], dtype=float32)>

In [46]:
#same seed same tensors
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(42)
random_tensor_4 = random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [47]:
#differen seed different tesnsors
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(15)
random_tensor_4 = random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>)

In [49]:
#creating tensors using zeors
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [50]:
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [51]:
#Tensors for all ones
tensor_ones=tf.ones(shape=(3,4),dtype=tf.dtypes.int16)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [53]:
import numpy as np
numpy_Array=np.arange(1,25,dtype=np.int16)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [54]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [59]:
print("Tesnor Information")
print("Shape:",tensor_numpy.shape)
print("Dimension: ",tensor_numpy.ndim)
print("Rank: ",tf.rank(tensor_numpy).numpy())
print("Size: ",tf.size(tensor_numpy))
print("DataType of elements: ",tensor_numpy.dtype)
print("Element along axis 0: ",tensor_numpy.shape[0])
print("Element along axis 1: ",tensor_numpy.shape[1])
print("Element along axis 2: ",tensor_numpy.shape[2])
print("Toatal number of element: \t ",tf.size(tensor_numpy).numpy())


Tesnor Information
Shape: (2, 3, 4)
Dimension:  3
Rank:  3
Size:  tf.Tensor(24, shape=(), dtype=int32)
DataType of elements:  <dtype: 'int16'>
Element along axis 0:  2
Element along axis 1:  3
Element along axis 2:  4
Toatal number of element: 	  24


In [60]:
#Working with items of each dimension
#first three elements
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [62]:
# first two elements of each dimension
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

## ** Arithmetic Operations with Tensors **

*   Add
*   Sub
*  Multi
*  Div




In [66]:
tensor_one=tf.constant([[11,9],[2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [72]:
#tensor_one+15
tf.add(tensor_one,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [73]:
#tensor_one-5
tf.subtract(tensor_one,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  4],
       [-3,  0]], dtype=int32)>

In [74]:
#tensor_one*2
tf.multiply(tensor_one,2)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 18],
       [ 4, 10]], dtype=int32)>

In [75]:
#tensor_one/2
tf.divide(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.5, 4.5],
       [1. , 2.5]])>

In [79]:
tensor_new=tf.square(tensor_one)
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [  4,  25]], dtype=int32)>

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [83]:
second_matrix=tf.constant([[8,16], [64,8.25],
                           [625,9.23],
                           [125,2.34],
                           [169,144]],dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[  8.    16.  ]
 [ 64.     8.25]
 [625.     9.23]
 [125.     2.34]
 [169.   144.  ]], shape=(5, 2), dtype=float32)


In [84]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 2.828427 ,  4.       ],
       [ 8.       ,  2.8722813],
       [25.       ,  3.0380914],
       [11.18034  ,  1.5297059],
       [13.       , 12.       ]], dtype=float32)>

**Exercise**
Create two tensors with random values between 0 and 1 , shape is [6,300]

**Find out the following details: **
* Number of elements
* Size,
* Rank,
* Shape
