In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('students.xlsx')
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


In [5]:
marks=df['Marks'].to_numpy()
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92 90 45]


In [6]:
print('Highest Marks ',np.max(marks))

Highest Marks  92


In [7]:
print('Lowest Marks ',np.min(marks))

Lowest Marks  45


In [9]:
print('Average Marks ',np.mean(marks))

Average Marks  80.0


# .loc: Label Based
# .iloc: index Based


In [23]:
print('original dataframe')
print(df)
print('Location : Label Based')
print(df.loc[2,['Name','Marks']])

original dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45
Location : Label Based
Name     Bob
Marks     78
Name: 2, dtype: object


In [26]:
print('original dataframe')
print(df)
print('Location : index Based')
print(df.iloc[2,[1,2]])

original dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45
Location : index Based
Age      21
Marks    78
Name: 2, dtype: object


# Axis in Numpy :
    1. Axis 0 : vertical direction: works column-wise
    2. Axis 1 : horizontal direction: works row-wise
    


# We have two students marks in 3 subjects
    # [[45,50,49],[30,45,49]]

    

In [30]:
marks_arr=np.array([[5,2,9],[10,40,60]])
print(marks_arr)

[[ 5  2  9]
 [10 40 60]]


In [31]:
print('Sum down each column',np.sum(marks_arr,axis=0))

Sum down each column [15 42 69]


In [32]:
print('Sum down each row',np.sum(marks_arr,axis=1))

Sum down each row [ 16 110]


In [33]:
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92 90 45]


In [34]:
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


# Find the Student Name who got highest marks

In [42]:
topper=df.loc[df['Marks'].idxmax(),'Name']
print(topper)

Sara


In [43]:
lastinclass=df.loc[df['Marks'].idxmin(),'Name']
print(lastinclass)

Rohit


In [47]:
print('Next Example')

Next Example


In [51]:
top_index = df['Marks'].idxmax()
top_student=df.iloc[top_index,df.columns.get_loc('Name')]
print('Topper of the Class is: ',top_student)

Topper of the Class is:  Sara
